models:
  ppa1026v3: '../workflow/data/models/Pichia_pastoris/iMT1026/Ppa_iMT1026v3_v2_read_write.xml'
  ppa1026: '../workflow/data/models/Pichia_pastoris/iMT1026/Ppa_iMT1026.xml'
  ppa1026Chan: '../workflow/data/models/Pichia_pastoris/iMT1026/Ppa_iMT1026_Chan2017.xml'
  ppaiLC915: '../workflow/data/models/Pichia_pastoris/iLC915/Ppa_iLC915_MODEL1507180065.xml'
  ppaMBEL1254: '../workflow/data/models/Pichia_pastoris/PpaMBEL1254/PpaMBEL1254.xml'
  ppaiPP668: 'in excel format'
  yli21_v1: '../workflow/data/models/Yarrowia_lipolytica/iYli21/iYli21_v1.xml'
  yli21: '../workflow/data/models/Yarrowia_lipolytica/iYli21/iYli21_v2.xml'
  yli4_uncorr: '../workflow/data/models/Yarrowia_lipolytica/iYali4/iYali4_uncorrected.xml'
  yli4_corr: '../workflow/data/models/Yarrowia_lipolytica/iYali4/iYali4_corr_v2.xml'
  yli2.0_corr: '../workflow/data/models/Yarrowia_lipolytica/iYli_2.0/iYli_2.0_corr_corr_v2.xml'
  yli2.0_uncorr: 'in excel format'
  yli647_uncorr: '../workflow/data/models/Yarrowia_lipolytica/iYLI647/iYLI647_uncorrected.xml'
  yli647_corr: '../workflow/data/models/Yarrowia_lipolytica/iYLI647/iYLI647_corr_corr.xml'
  iYL619_PCP: '../workflow/data/models/Yarrowia_lipolytica/iYL619_PCP/iYL619_PCP.xml'
  yliMK735_corr: '../workflow/data/models/Yarrowia_lipolytica/iMK735/iMK735_corr.xml'
  yliMK735_uncorr: '../workflow/data/models/Yarrowia_lipolytica/iMK735/Yli_iMK735_v2.xml'
  yliNL895_corr: '../workflow/data/models/Yarrowia_lipolytica/iNL895/iNL895_corr.xml'
  yliNL895_uncorr: '../workflow/data/models/Yarrowia_lipolytica/iNL895/Yli_iNL895.xml'
  ecc: '../workflow/data/models/0test/Ecoli/e_coli_core.xml'
  ecoli: '../workflow/data/models/0test/Ecoli/iAF1260.xml'
  scere: '../workflow/data/models/0test/Scerevisiae/iMM904.xml'
seperator: ';'
experiments:
  growth_simulation_table: '../workflow/data/growth_simulation/experimental_growth_table_Yli.csv'
  yli_glucose_growth: '../results/FBA_results/glucose_simulated_growth_rates.csv'
  yli_fructose_growth: '../results/FBA_results/fructose_simulated_growth_rates.csv'
  yli_growth: '../results/FBA_results/experimental_vs_simulation/'
  reaction_table: '../workflow/data/metabolic_maps/glycolysis_citrate_table.csv'
  efm_decomposition:
    coefs: data/EFM_decomposition/coefs.npy
    efms: data/EFM_decomposition/efms.npy
    optimal_vector: data/EFM_decomposition/optimal_vector.npy
  PhPP:
    min_glu: 0.0101
    max_glu: 3.5 # 5
    min_oxy: 0.101 # 0.38
    max_oxy: 6 # 10
    number_computations: 30
results:
  metabolic_fluxes: '../workflow/results/FBA_results/metabolic_fluxes'
  metabolic_comparison_condition: '../workflow/results/FBA_results/central_carbon_metabolism_fva.csv'
  model_errors: '../workflow/results/quality/model_error_table.csv'
  model_errors: '../workflow/results/quality/model_error_table.csv'
  model_numbers: '../workflow/results/quality/number_tables/working_model_numbers.csv' # directory for the model's number of genes, reactions, metabolites, compartments
  model_numbers_directory: '../workflow/results/quality/number_tables/' # directory for the model's number of genes, reactions, metabolites, compartments
  EFM_model_dir: '../workflow/data/models/EFM_decomp/'
general:
  verbose: False
  snakemake: True
  show_plot: False
  store_results: True
  loopless: True
  condition_name: 'all_031_maintenance_789'
verbose: False